title: It's a site
email: elli_mylonas@brown.edu
description: > # this means to ignore newlines until "baseurl:"
  This site exists only on github, editing in teh repo
baseurl: "/themes-test"
twitter_username: elli-m
github_username:  emylonas

# Build settings
markdown: kramdown
theme: jekyll-theme-dinky
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
